# Generated by Django 4.2.3 on 2024-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_alter_user_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Sabzevar', 'سبزوار'), ('Tehran', 'تهران'), ('Karaj', 'کرج'), ('Mashhad', 'مشهد'), ('neyshabor', 'نیشابور'), ('Yazd', 'یزد')], default='سبزوار', max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_post',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کدپستی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+98', max_length=15, verbose_name='تلفن همراه'),
        ),
    ]
