# Generated by Django 4.2.3 on 2024-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_user_city_user_code_post_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+98', max_length=16, verbose_name='تلفن همراه'),
        ),
    ]
