# Generated by Django 4.2.3 on 2024-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[['Sabzevar', 'سبزوار'], ['Tehran', 'تهران'], ['Karaj', 'کرج'], ['Mashhad', 'مشهد'], ['neyshabor', 'نیشابور'], ['Yazd', 'یزد']], default='سبزوار', max_length=100, verbose_name='شهر'),
        ),
    ]
