# Generated by Django 4.2.3 on 2024-01-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[['Woman', 'زن'], ['man', 'مرد'], ['unknown', 'نامشخص'], ['dont_say', 'نمی خواهم بگویم']], default='نامشخص', max_length=50, verbose_name='جنسیت'),
        ),
    ]
