# Generated by Django 4.2.3 on 2024-01-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0039_alter_product_code_product'),
        ('user_module', '0007_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='products_module.product', verbose_name='علاقه مندی ها'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
