# Generated by Django 4.2.3 on 2024-01-26 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0010_remove_user_favorites_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('2d8b31b5-ce42-463c-b126-39d54f4a162d')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
