# Generated by Django 4.2.3 on 2024-01-26 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0011_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('88a1a4a3-4d6b-4401-8bca-052b336c750a')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
