# Generated by Django 4.2.3 on 2024-01-31 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0013_alter_user_code_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('e7ab285c-856b-47f1-99aa-5a47dde7aeb2')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
