# Generated by Django 4.2.3 on 2024-01-31 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0014_comments_reply_alter_user_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('d57a9184-8ddb-4d34-b8b6-433483becf8c')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
