# Generated by Django 4.2.3 on 2024-02-01 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0015_comments_date_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('5837656a-7443-4a13-9b21-08106b98cb56')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
