# Generated by Django 4.2.3 on 2024-02-01 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0016_alter_comments_options_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('e9500edd-760d-42d9-a707-dcab9861d2de')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
