# Generated by Django 4.2.3 on 2024-02-01 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0017_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_module.comments', verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('9e7e5764-303c-423a-a76b-80080c0e5f75')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
