# Generated by Django 4.2 on 2024-02-21 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0054_alter_product_code_product'),
        ('user_module', '0020_alter_user_code_user_compare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compare',
            options={'verbose_name': 'مقایسه', 'verbose_name_plural': 'مقایسه ها'},
        ),
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ManyToManyField(limit_choices_to={'id__lte': 4}, related_name='product', to='products_module.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('e4b70aad-5da5-4939-9ffd-738bf5cf1b34')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
