# Generated by Django 4.2 on 2024-02-22 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0055_alter_product_code_product'),
        ('user_module', '0021_alter_compare_options_alter_compare_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ManyToManyField(related_name='product', to='products_module.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('176060c9-a3f0-42af-bb40-e7d58647b72c')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
