# Generated by Django 4.2 on 2024-02-25 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0022_alter_compare_product_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('32d7b3a6-3269-4bd6-8ad2-75399165451c')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
