# Generated by Django 4.2 on 2024-02-26 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0023_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('ed7b837b-6e95-490c-b3b2-3164e689ae0e')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
