# Generated by Django 4.2.3 on 2024-03-05 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0058_alter_product_code_product'),
        ('user_module', '0024_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='product',
            field=models.ManyToManyField(related_name='product_ol', to='products_module.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('25c469b6-66a2-4cac-9a55-45f6ca2bdd14')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
