# Generated by Django 4.2.3 on 2024-03-12 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0025_alter_compare_product_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('73f32dd2-2b9b-414f-88b0-61bdb193a8e2')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
