# Generated by Django 4.2.3 on 2024-03-14 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0027_alter_user_code_user_mostpopular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('8d4aca87-5b14-4055-9558-74ca46f1cbf4')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
