# Generated by Django 4.2.3 on 2024-03-15 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0028_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('06fad034-ade5-4c15-a3e0-bf7d40d11b00')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
