# Generated by Django 4.2.3 on 2024-03-15 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0029_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('17fb4b9e-7b53-4740-a50f-534d158e5090')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
