# Generated by Django 4.2.3 on 2024-03-15 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0030_alter_user_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='AutoDeleteAccount',
            field=models.BooleanField(default=False, verbose_name='حذف خود کار کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='showEmail',
            field=models.BooleanField(default=False, verbose_name='نمایش ایمیل'),
        ),
        migrations.AddField(
            model_name='user',
            name='showImageProfile',
            field=models.BooleanField(default=False, verbose_name='نمایش عکس پروفایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='showProfile',
            field=models.BooleanField(default=False, verbose_name='نمایش پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('491c501f-da31-4854-9522-08e725286692')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
