# Generated by Django 4.2.3 on 2024-03-15 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0031_user_autodeleteaccount_user_showemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AutoDeleteAccount',
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('03f89c70-4a32-4f57-9f64-692aa980edff')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
