# Generated by Django 4.2.3 on 2024-03-18 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0032_remove_user_autodeleteaccount_alter_user_code_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='showEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='showImageProfile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='showProfile',
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('78dcc7ab-7c5c-4566-983b-cdd7d1200d7a')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
