# Generated by Django 4.2.3 on 2024-03-19 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0033_remove_user_showemail_remove_user_showimageprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('bfc0860a-390b-4ddc-ac2a-80f7625be8bc')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
