# Generated by Django 4.2.3 on 2024-03-19 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0034_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('d2db7a5f-8292-486c-aac5-18c3141c3695')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
