# Generated by Django 4.2.3 on 2024-03-19 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0035_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('2ad49599-d9f3-402a-9ce9-8a76a6238b0d')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
