# Generated by Django 4.2.3 on 2024-03-19 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0036_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('068a0598-e86d-4d48-b51a-f83429681734')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
