# Generated by Django 4.2.3 on 2024-03-20 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0037_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('82d6fe02-9268-40a9-b19a-f2da099bd0ff')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
