# Generated by Django 4.2.3 on 2024-03-20 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0038_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('6a2a6767-2985-4eec-95da-3f487064130a')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
