# Generated by Django 4.2.3 on 2024-03-21 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0039_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('260933d7-558a-42c8-afcb-76296f7c59c6')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
