# Generated by Django 4.2.3 on 2024-03-24 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0041_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('d55df585-a8ac-4018-b2cb-89fbf35b1e3a')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
