# Generated by Django 4.2.3 on 2024-03-24 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0042_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('32b9f079-9390-48a8-9980-b0e3d608156a')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
