# Generated by Django 4.2.3 on 2024-03-24 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0043_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('6ec99944-920b-4390-95b3-b4c070d1f109')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
