# Generated by Django 4.2.3 on 2024-03-25 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0044_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('7df89d61-637e-43e2-887f-66fea22bf78e')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
