# Generated by Django 4.2.3 on 2024-03-25 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0045_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('19a13f3a-7482-4deb-ac79-6bbbebb8edff')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
