# Generated by Django 4.2.3 on 2024-03-25 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0046_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('e6fe7ec7-e861-4d51-ae29-361149c7af3b')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
