# Generated by Django 4.2.3 on 2024-03-25 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0047_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('62cc65f5-efcd-4ccd-b401-5802b62c811f')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
