# Generated by Django 4.2.3 on 2024-03-25 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0050_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('5c799347-0358-49cc-ae2f-f4441bf30cfe')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
