# Generated by Django 4.2.3 on 2024-03-25 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0051_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('cbc215c0-0c9d-4da3-9a40-738a24fef031')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
