# Generated by Django 4.2.3 on 2024-03-25 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0053_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('d2a5fc3f-5032-472f-b9f0-a0d4b0e21f07')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
