# Generated by Django 4.2.3 on 2024-03-25 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0054_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('5b575190-d444-4493-a74d-dd9c673a88f6')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
