# Generated by Django 4.2.3 on 2024-03-25 19:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0055_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('4400b061-d1c3-4125-a9ff-dbc3a2aad0d9')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
