# Generated by Django 4.2.3 on 2024-03-25 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0057_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('f5339ba7-709d-4fad-8f15-4227bf3cdc04')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
