# Generated by Django 4.2.3 on 2024-03-26 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0058_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='', null=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_post',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='کدپستی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('fc770d35-70f0-4f1a-9110-944316e5b658')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
