# Generated by Django 4.2.3 on 2024-03-26 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0059_alter_user_address_alter_user_code_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('c0f05a88-6910-415a-ab1e-1c66bba36f59')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
