# Generated by Django 4.2.3 on 2024-03-26 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0060_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('7921cc3b-d326-4c1a-b953-8aba64d13bb9')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
