# Generated by Django 4.2.3 on 2024-03-26 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0061_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('9ea69898-a97e-44c6-9842-5ee58e0e5bb5')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
