# Generated by Django 4.2.3 on 2024-03-26 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0062_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('16cb5b41-1671-4647-8f6c-74f4e4eee889')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
