# Generated by Django 4.2 on 2024-03-28 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0064_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('90e11c15-863e-4127-85b3-98613edb7d13')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
