# Generated by Django 5.0.4 on 2024-06-23 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0065_alter_user_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_user',
            field=models.CharField(default=[uuid.UUID('f17b8d2d-641d-402a-a6cd-a9d09d2c5231')], max_length=20, verbose_name='کد کاربر'),
        ),
    ]
