# Generated by Django 4.2.3 on 2023-12-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
                ('url', models.CharField(default=models.CharField(max_length=50, verbose_name='نام دسته بندی'), max_length=60, verbose_name='نام در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tage', models.CharField(max_length=50, verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=60, verbose_name='نام بلاگ')),
                ('image', models.ImageField(upload_to='Blogs/%Y', verbose_name='عکس')),
                ('date', models.DateField(auto_now_add=True)),
                ('short_description', models.CharField(max_length=100, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('quote', models.CharField(max_length=200, verbose_name='نقل قول')),
                ('author_quote', models.CharField(max_length=50, verbose_name='نویسنده نقل قول')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده بلاگ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs_module.blogcategory', verbose_name='دسته بندی')),
                ('tage', models.ManyToManyField(to='blogs_module.blogtags', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
