# Generated by Django 4.2.3 on 2023-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='url',
            field=models.CharField(max_length=60, verbose_name='نام در url'),
        ),
    ]
