# Generated by Django 4.2.3 on 2023-12-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0002_alter_blogcategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='quote',
            field=models.CharField(max_length=300, verbose_name='نقل قول'),
        ),
    ]
