# Generated by Django 4.2.3 on 2023-12-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0003_alter_blogs_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='list_page_description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='توضیحات در صفحه بلاگ لیست'),
        ),
    ]
