# Generated by Django 4.2.3 on 2023-12-18 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0005_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7170d03b-9a32-4458-80a1-e97d6b92831f'), null=True, unique=True, verbose_name=''),
        ),
    ]
