# Generated by Django 4.2.3 on 2023-12-18 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0006_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c804d8b9-f2d1-4279-a0db-be0c12b69400'), null=True, unique=True, verbose_name=''),
        ),
    ]
