# Generated by Django 4.2.3 on 2023-12-18 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0007_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ade71f1e-2c05-4497-9838-c496cb61b4a3'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
