# Generated by Django 4.2.3 on 2023-12-18 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0008_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bfc779e1-1a43-4ed2-8338-40134a1283c7'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
