# Generated by Django 4.2.3 on 2023-12-23 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0010_moredetail_alter_blogs_slug_blogs_more_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moredetail',
            options={'verbose_name': 'توزیح', 'verbose_name_plural': 'توضیحات'},
        ),
        migrations.AddField(
            model_name='moredetail',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cefc3b95-7a92-4d45-b1d1-8275eb99596b'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
