# Generated by Django 4.2.3 on 2023-12-24 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0012_remove_blogs_more_detail_remove_moredetail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c89ab148-4180-414c-9505-62c0e2a10d03'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
