# Generated by Django 4.2.3 on 2023-12-25 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0013_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e95720c5-e8f6-4856-a2fb-dc77f0533bfc'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
