# Generated by Django 4.2.3 on 2023-12-25 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0014_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f3f35c51-247e-40ca-a760-44533e50d220'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
