# Generated by Django 4.2.3 on 2023-12-26 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0015_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bf2bf7b3-9f01-403e-9161-3ca337fdedf2'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
