# Generated by Django 4.2.3 on 2023-12-26 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0016_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8aa27be7-223a-4449-aea1-d091a1dfc204'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
