# Generated by Django 4.2.3 on 2023-12-27 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0017_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('530518f8-ec58-46aa-9cbe-286adfed7527'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
