# Generated by Django 4.2.3 on 2023-12-27 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0018_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0f3976e2-566a-4216-84c3-c9687a22bfbd'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
