# Generated by Django 4.2.3 on 2023-12-27 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0019_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('231e93a6-052b-4708-9e84-812ff8f23d9c'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
