# Generated by Django 4.2.3 on 2023-12-27 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0020_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('899c397c-52c6-424c-92c5-5263b2cff904'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
