# Generated by Django 4.2.3 on 2023-12-27 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0022_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b7fb38d8-da65-4ef4-8898-98503c36f3f1'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
