# Generated by Django 4.2.3 on 2024-01-03 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0023_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('426a7ec4-af0c-439f-b879-f3de152dc422'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
