# Generated by Django 4.2.3 on 2024-01-08 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0024_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('535cd122-47dc-4ffa-8a19-6c6374247f82'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
