# Generated by Django 4.2.3 on 2024-01-16 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0025_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0d8eed92-2cef-4f3c-9f95-daf9b1454d18'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
