# Generated by Django 4.2.3 on 2024-01-16 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0026_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2a05b2db-99ab-4032-ae16-3d559797fbe4'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
