# Generated by Django 4.2.3 on 2024-01-16 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0027_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a97f4fc5-1c6d-47ca-a268-13a7f349136d'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
