# Generated by Django 4.2.3 on 2024-01-16 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0028_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('56c40326-4826-4bb3-9a39-f192bd494f7f'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
