# Generated by Django 4.2.3 on 2024-01-16 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0029_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8521be59-a04b-4536-af7d-8fbc51f9c0f8'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
