# Generated by Django 4.2.3 on 2024-01-16 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0030_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5a4e318d-b3d0-4012-ab65-de8462abfbe1'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
