# Generated by Django 4.2.3 on 2024-01-24 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0032_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('991b283e-6a06-43e8-a4df-9695f3d3a3dd'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
