# Generated by Django 4.2.3 on 2024-01-24 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0033_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ec11701c-96ff-48a5-94e1-65fb97cbfc1b'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
