# Generated by Django 4.2.3 on 2024-01-24 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0034_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9806d445-6a1a-4353-a505-5aadf6cacff3'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
