# Generated by Django 4.2.3 on 2024-01-24 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0035_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('35b0792f-e1ee-4ec8-a00a-451e8f703325'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
