# Generated by Django 4.2.3 on 2024-01-24 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0036_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f4c2cdb4-c159-4c85-9b03-39f1903cf40b'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
