# Generated by Django 4.2.3 on 2024-01-24 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0037_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6d66ebdb-9343-4844-959d-2ead05001b02'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
