# Generated by Django 4.2.3 on 2024-01-24 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0038_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('30a42687-32df-4e80-93b8-55e7393cbecf'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
