# Generated by Django 4.2.3 on 2024-01-24 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0039_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cd7b1440-3a38-40cf-8cc5-47e600479ce0'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
