# Generated by Django 4.2.3 on 2024-01-26 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0042_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b8feebec-649d-4b06-8977-92bc70abf430'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
