# Generated by Django 4.2.3 on 2024-01-26 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0043_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('83fed1ed-0853-4627-bdd4-287b00867b96'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
