# Generated by Django 4.2.3 on 2024-01-31 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs_module', '0044_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4755e8fb-14dd-4dba-94b3-a64cbcd01cb0'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('check_by_admin', models.BooleanField(default=False, verbose_name='تایید توسط ادمین')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs_module.blogs', verbose_name='بلاگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
