# Generated by Django 4.2.3 on 2024-01-31 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0045_alter_blogs_slug_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8d473bba-11b0-4eb0-863e-4be176b706eb'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
