# Generated by Django 4.2.3 on 2024-01-31 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0046_commentblog_reply_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8856e288-6521-4317-a2b7-fb8b8f166705'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
