# Generated by Django 4.2.3 on 2024-02-01 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0047_commentblog_date_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b0942b16-776d-4bb1-a66c-44e87feebd49'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
