# Generated by Django 4.2.3 on 2024-02-01 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0048_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ff1d7fa0-0f66-4ecc-8edf-f555d39d58de'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
