# Generated by Django 4.2.3 on 2024-02-01 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0049_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentblog',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ff87688e-3a1b-4d30-b5d0-d7680072a897'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs_module.commentblog', verbose_name='پاسخ'),
        ),
    ]
