# Generated by Django 4.2.3 on 2024-02-05 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0050_alter_commentblog_options_alter_blogs_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0b87b0bf-6cff-4425-9b7f-714e8a111842'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
