# Generated by Django 4.2 on 2024-02-20 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0051_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a863ec00-f5e4-48d6-820c-b2d60eb39aea'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
