# Generated by Django 4.2 on 2024-02-21 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0052_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('064b090e-e49b-4598-8a51-eca8a96bbd65'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
