# Generated by Django 4.2 on 2024-02-22 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0053_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6fd680fa-26a4-4912-af73-e0b127b41488'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
