# Generated by Django 4.2 on 2024-02-25 14:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0054_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('80f7f38b-96c6-43ef-8a62-49c813d56f81'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
