# Generated by Django 4.2 on 2024-02-26 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0055_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3943ff7a-b446-482b-9031-5bfaaa147895'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
