# Generated by Django 4.2.3 on 2024-03-05 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0056_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a06492fb-73c7-4313-b290-95e623b63a66'), null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
