# Generated by Django 4.2.3 on 2024-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0057_alter_blogs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
