# Generated by Django 4.2.3 on 2024-03-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_module', '0058_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_view',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد بازدید از بلاگ'),
        ),
        migrations.CreateModel(
            name='BlogMostPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.GenericIPAddressField(verbose_name='ای پی کاربر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs_module.blogs', verbose_name='بلاگ')),
            ],
        ),
    ]
