# Generated by Django 4.2.3 on 2023-12-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='شماره تلفن'),
        ),
    ]
