# Generated by Django 4.2.3 on 2023-12-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_contactus_email_alter_contactus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
