# Generated by Django 4.2.3 on 2024-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='home_images', verbose_name='ایکون')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره پشتیبانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت صفحه خانه',
                'verbose_name_plural': 'تنظیمات سایت صفحه خانه',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('product_list', 'product_list'), ('product_details', 'product_details')], max_length=50, verbose_name='صفحه')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='عکس')),
                ('description', models.TextField(default='', verbose_name='توضیحات')),
                ('short_description', models.CharField(default='', max_length=100, verbose_name='توضیحات کوتاه')),
                ('title', models.CharField(default='', max_length=100, verbose_name='کلمات کلیدی')),
                ('url', models.CharField(max_length=100, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنضیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_images', verbose_name='عکس')),
                ('description', models.TextField(default='', verbose_name='توضیحات')),
                ('short_description', models.CharField(default='', max_length=100, verbose_name='توضیحات کوتاه')),
                ('title', models.CharField(default='', max_length=100, verbose_name='کلمات کلیدی')),
                ('url', models.CharField(max_length=100, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'تبلیغات صفحه خانه',
                'verbose_name_plural': 'تبلیغات صفحه خانه',
            },
        ),
        migrations.AddConstraint(
            model_name='sitesettingshome',
            constraint=models.CheckConstraint(check=models.Q(('pk__lt', 14)), name='max_items_limit2'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(check=models.Q(('pk__lt', 3)), name='max_items_limit3'),
        ),
        migrations.AddConstraint(
            model_name='homesettings',
            constraint=models.CheckConstraint(check=models.Q(('pk__lt', 2)), name='max_items_limit1'),
        ),
    ]
