# Generated by Django 4.2.3 on 2024-03-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sitesettingshome',
            name='max_items_limit2',
        ),
        migrations.AddConstraint(
            model_name='sitesettingshome',
            constraint=models.CheckConstraint(check=models.Q(('id__lt', 14)), name='max_items_limit2'),
        ),
    ]
