# Generated by Django 4.2.3 on 2024-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_remove_sitesettingshome_max_items_limit2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingshome',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='کلمات کلیدی'),
        ),
    ]
