# Generated by Django 4.2.3 on 2024-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_sitesettingshome_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingshome',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='sitesettingshome',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='توضیحات کوتاه'),
        ),
    ]
