# Generated by Django 4.2.3 on 2024-03-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_sitesettingshome_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='icon_phone',
            field=models.ImageField(null=True, upload_to='home_images', verbose_name='ایکون پشتیبانی'),
        ),
    ]
