# Generated by Django 4.2.3 on 2024-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_remove_homesettings_max_items_limit1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='کلمات کلیدی'),
        ),
    ]
