# Generated by Django 4.2.3 on 2024-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_sitesettings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
    ]
