# Generated by Django 4.2.3 on 2024-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_homesettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='فیسبوک'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='pinterest',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='پینترست'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='twitter',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='توییتر'),
        ),
    ]
