# Generated by Django 4.2.3 on 2024-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_homesettings_address_homesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='link',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='لینک'),
        ),
    ]
