# Generated by Django 4.2.3 on 2024-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_homesettings_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='user_description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
    ]
