# Generated by Django 4.2.3 on 2024-03-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_homesettings_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='user_profile_description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات در داشبورد کاربر بخش پروفایل'),
        ),
        migrations.AlterField(
            model_name='homesettings',
            name='user_description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات در داشبورد کاربر'),
        ),
    ]
