# Generated by Django 4.2.3 on 2024-03-21 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_module', '0076_alter_product_code_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketBuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت کل')),
                ('number_product', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.PositiveIntegerField(verbose_name='جمع نهایی')),
                ('cart', models.ManyToManyField(to='order_success_module.basketbuymodel', verbose_name='سبد خرید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
    ]
