# Generated by Django 4.2.3 on 2024-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_success_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='جمع نهایی'),
        ),
    ]
