# Generated by Django 4.2.3 on 2024-03-25 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_success_module', '0003_ordersuccess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderSuccess',
            new_name='OrderSuccessModel',
        ),
    ]
