# Generated by Django 4.2.3 on 2024-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_success_module', '0004_rename_ordersuccess_ordersuccessmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersuccessmodel',
            name='order',
            field=models.ManyToManyField(null=True, to='order_success_module.basketbuymodel', verbose_name='سبد خرید'),
        ),
    ]
