# Generated by Django 4.2.3 on 2024-03-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_success_module', '0005_ordersuccessmodel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersuccessmodel',
            name='order',
        ),
    ]
