# Generated by Django 4.2.3 on 2024-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_success_module', '0006_remove_ordersuccessmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketbuymodel',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
    ]
