# Generated by Django 4.2.3 on 2023-12-24 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن')),
                ('icon', models.ImageField(upload_to='about/delivery', verbose_name='ایکون')),
            ],
            options={
                'verbose_name': 'جزئیات تحویل',
                'verbose_name_plural': 'جزئیات تحویل',
            },
        ),
        migrations.CreateModel(
            name='CustomerTurst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='موضوع')),
                ('text', models.CharField(max_length=700, verbose_name='متن')),
                ('text_shadow', models.CharField(help_text='نوشته سایه مانند در گوشه سمت چپ کارت ها', max_length=6, verbose_name='راهنمایی')),
                ('icon', models.ImageField(upload_to='about/customer', verbose_name='ایکون')),
            ],
            options={
                'verbose_name': 'اعتماد مشتری',
                'verbose_name_plural': 'اعتماد مشتریان',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image1', models.ImageField(upload_to='about/main', verbose_name='عکس اول')),
                ('image2', models.ImageField(upload_to='about/main', verbose_name='عکس دوم')),
                ('customer_turst', models.ManyToManyField(to='about_module.customerturst', verbose_name='اعتماد مشتریان')),
                ('delivery_detail', models.ManyToManyField(to='about_module.aboutdelivery', verbose_name='جزئیات تحویل')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
