# Generated by Django 4.2.3 on 2023-12-16 08:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='نام محصول')),
                ('image', models.ImageField(upload_to='product/%Y/%b', verbose_name='عکس')),
                ('image_sub', models.ImageField(blank=True, upload_to='product/%Y/%b', verbose_name='عکس فرعی')),
                ('image_sub2', models.ImageField(blank=True, upload_to='product/%Y/%b', verbose_name='عکس فرعی2')),
                ('image_sub3', models.ImageField(blank=True, upload_to='product/%Y/%b', verbose_name='عکس فرعی 3')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount', models.PositiveIntegerField(verbose_name='تخفیف')),
                ('weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='وزن')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن محصول')),
                ('code_product', models.CharField(default='8LBMYfLfza', max_length=11, unique=True, verbose_name='کد محصول')),
                ('is_active', models.BooleanField(default=False, verbose_name='موجود بودن محصول')),
                ('score', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(5)], verbose_name='امتیاز')),
                ('size_box', models.CharField(choices=[('400-500', '400 تا 500 گرم'), ('500-700', '500 تا 700 گرم'), ('700-1kg', '700 تا 1 کیلوگرم'), ('120-150g(two boxes)', '120 تا 150 گرم دو بسته')], max_length=70, verbose_name='سایز جعبه')),
                ('product_number', models.PositiveIntegerField(verbose_name='تعداد محصول')),
                ('title_des', models.CharField(blank=True, max_length=30, null=True, verbose_name='موضوع توضیحات')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image_description', models.ImageField(blank=True, upload_to='product/description/%b', verbose_name='عکس در توضیحات')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('is_delete', models.BooleanField(default=False, verbose_name='پاک شدن محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product_categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع')),
                ('url', models.CharField(help_text='english name category', max_length=30, verbose_name='نام در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tage', models.CharField(max_length=30, verbose_name='نام تگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.product', verbose_name='محصول مورد نظر')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_feature', models.CharField(max_length=50, verbose_name='نام ویژگی')),
                ('attribute_value', models.CharField(max_length=60, verbose_name='مقدار ویزگی')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.product', verbose_name='محصول مورد نظر')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.product_categorys', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=100, verbose_name='دستور عمل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_module.product', verbose_name='محصول مورد نظر')),
            ],
            options={
                'verbose_name': 'دستور العمل',
                'verbose_name_plural': 'دستور العمل ها',
            },
        ),
    ]
