# Generated by Django 4.2.3 on 2023-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='zXRMDK1r7Q', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
