# Generated by Django 4.2.3 on 2023-12-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0003_product_categorys_image_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='1hpkKz3VUD', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
