# Generated by Django 4.2.3 on 2023-12-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0004_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='m3YTYqHx4u', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
