# Generated by Django 4.2.3 on 2023-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0014_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='qO6lWi7AGb', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
