# Generated by Django 4.2.3 on 2023-12-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0017_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='N2cPAap7I9', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
