# Generated by Django 4.2.3 on 2023-12-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0019_product_is_vegetarian_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='GBQtY553xv', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='آیا گیاهخوار هستید؟'),
        ),
    ]
