# Generated by Django 4.2.3 on 2023-12-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0020_alter_product_code_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diet',
            field=models.BooleanField(default=False, verbose_name='رژیم غذایی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='3iOMJbw8_X', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
