# Generated by Django 4.2.3 on 2023-12-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0021_product_diet_alter_product_code_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_vegetarian',
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='qwML51hexY', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
