# Generated by Django 4.2.3 on 2023-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0022_remove_product_is_vegetarian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tags',
            name='url',
            field=models.CharField(max_length=30, null=True, verbose_name='نام در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='vOG0LO-fZE', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
