# Generated by Django 4.2.3 on 2023-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0023_product_tags_url_alter_product_code_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tags',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tage',
            field=models.ManyToManyField(to='products_module.product_tags', verbose_name='تگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='YYpc2fWpp9', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
