# Generated by Django 4.2.3 on 2024-01-03 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0024_remove_product_tags_product_product_tage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='ygz4nEeVb8', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
