# Generated by Django 4.2.3 on 2024-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0025_alter_product_code_product_alter_product_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='9M8t_UJA_n', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
