# Generated by Django 4.2.3 on 2024-01-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0035_alter_favorites_product_alter_favorites_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='d5BX2dMZF-', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
