# Generated by Django 4.2.3 on 2024-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0051_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='Cs46ZLFdO5', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
