# Generated by Django 4.2 on 2024-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0056_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='7ouPgv2ggV', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
