# Generated by Django 4.2.3 on 2024-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0064_alter_product_code_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_product',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعدا بازدید از محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='fLRnEtSaId', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
