# Generated by Django 4.2.3 on 2024-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0065_product_view_product_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='lkF1pKWiMk', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
