# Generated by Django 4.2.3 on 2024-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0069_alter_product_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='9Mmzf78Zpu', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_sub',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%b', verbose_name='عکس فرعی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_sub2',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%b', verbose_name='عکس فرعی2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_sub3',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%b', verbose_name='عکس فرعی 3'),
        ),
    ]
