# Generated by Django 4.2.3 on 2024-03-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0070_alter_product_code_product_alter_product_image_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='Dk113gX8K5', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(null=True, verbose_name='تخفیف'),
        ),
    ]
