# Generated by Django 4.2.3 on 2024-03-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0072_alter_product_code_product_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='sROzDaspne', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='تخفیف'),
        ),
    ]
