# Generated by Django 4.2.3 on 2024-03-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0077_alter_product_code_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='aO_Ugu3a4s', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
