# Generated by Django 4.2.3 on 2024-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0078_product_sales_alter_product_code_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proposal',
            field=models.BooleanField(default=False, verbose_name='محصول پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='mqrUdFrG52', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
