# Generated by Django 4.2.3 on 2024-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0080_alter_product_code_product_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='cqaADA-vKI', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
