# Generated by Django 5.0.4 on 2024-06-23 17:43

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_module', '0101_alter_product_code_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(default='fIq5PC-udP', max_length=11, unique=True, verbose_name='کد محصول'),
        ),
    ]
